export const mockData = {
  results: [
    {
      uri: "nyt://article/5ae7e1ae-14b2-5913-b72d-2115d31265dc",
      url: "https://www.nytimes.com/2024/09/28/well/eat/what-is-dash-diet.html",
      id: 100000009691489,
      asset_id: 100000009691489,
      source: "New York Times",
      published_date: "2024-09-28",
      updated: "2024-09-28 05:01:58",
      section: "Well",
      subsection: "Eat",
      nytdsection: "well",
      adx_keywords:
        "Diet and Nutrition;Blood Pressure;Cooking and Cookbooks;Vegetables;Recipes;Content Type: Service;Research;Fruit;Clinical Trials;Hypertension",
      column: null,
      byline: "By Alice Callahan",
      type: "Article",
      title: "The Heart-Healthy Diet Hardly Anyone Is Talking About",
      abstract:
        "The DASH diet was shown to lower blood pressure decades ago, yet few people follow it. Here’s how to give it a try.",
      des_facet: [
        "Diet and Nutrition",
        "Blood Pressure",
        "Cooking and Cookbooks",
        "Vegetables",
        "Recipes",
        "Content Type: Service",
        "Research",
        "Fruit",
        "Clinical Trials",
        "Hypertension",
      ],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Giacomo Bagnara",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2024/09/28/well/28Well-DASH/28Well-DASH-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2024/09/28/well/28Well-DASH/28Well-DASH-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2024/09/28/well/28Well-DASH/28Well-DASH-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
  ],
  copyright: "copyright",
};
